
# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Pull Request Builds

on: [pull_request]
permissions:
  checks: write
  contents: read
  actions: read

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
        cache: 'gradle'
    - name: Grant execute permission to gradlew
      run: chmod +x gradlew
    - name: Build and test with Gradle
      run: ./gradlew build runGametest
    - uses: actions/upload-artifact@v4
      with:
        name: "Compiled artifacts for Pull Request #${{github.event.number}}"
        path: build/libs
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: "Test results for Pull Request #${{github.event.number}}"
        path: build/junit.xml
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Gametests            # Name of the check run which will be created
        path: build/junit.xml    # Path to test results
        reporter: java-junit        # Format of test results
